# Generated by Django 4.2.18 on 2025-07-11 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedpdf',
            options={'verbose_name': '上傳 PDF', 'verbose_name_plural': '上傳 PDF 列表'},
        ),
    ]
