# Generated by Django 4.2.18 on 2025-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0002_alter_uploadedpdf_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedpdf',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
