# Generated by Django 4.2.18 on 2025-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0003_uploadedpdf_display_name_uploadedpdf_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
