# Generated by Django 4.2.18 on 2025-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slides', '0004_uploadedpdf_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='last_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
